;;; init-meow.el -- Init File. -*- lexical-binding: t -*-
;;; Commentary:

(setup meow
  (:once (list :hooks 'window-setup-hook)
    (require 'meow))
  (:option*
   meow-esc-delay 0.001
   meow-char-thing-table
	 '((?\( .	round)
		 (?\) .	round)
		 (?\" . string)
		 (?\[ .	square)
		 (?\] .	square)
		 (?<  .	angle)
		 (?>  .	angle)
		 (?{  .	curly)
		 (?}  .	curly)
		 (?s  .	symbol)
		 (?f  .	defun)
		 (?w  .	window)
		 (?l  .	line)
		 (?b  .	buffer)
		 (?p  .	paragraph)))
	(:doc "setup meow common setting")
  (:when-loaded
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-colemak)
		(let ((mode-pairs '(
												(dashboard-mode . motion)
												(info-mode . normal)
												(calculator-mode . insert)
												(cargo-process-mode . motion)
												(benchmark-init/tabulated-mode . normal)
												(benchmark-init/tree-mode . normal))))
			(dolist (x mode-pairs)
				(add-to-list 'meow-mode-state-list x)))
    (unless (bound-and-true-p meow-global-mode)
      (meow-global-mode 1)))
	(:doc "setup meow normal keybindings")
	(:when-loaded
		(meow-normal-define-key
		 '("?" . meow-keypad-describe-key)
		 '("1" . select-window-or-expand-1)
		 '("2" . select-window-or-expand-2)
		 '("3" . select-window-or-expand-3)
		 '("4" . select-window-or-expand-4)
		 '("5" . select-window-or-expand-5)
		 '("6" . select-window-or-expand-6)
		 '("7" . select-window-or-expand-7)
		 '("8" . select-window-or-expand-8)
		 '("9" . select-window-or-expand-9)
		 '("0" . select-window-or-expand-0)
		 '("-" . negative-argument)
		 '(";" . meow-reverse)
		 '("," . meow-inner-of-thing)
		 '("." . meow-bounds-of-thing)
		 '("/" . meow-visit)
		 '("[" . meow-beginning-of-thing)
		 '("]" . meow-end-of-thing)
		 '("a" . meow-append)
		 '("A" . meow-open-below)
		 '("b" . meow-back-word)
		 '("B" . meow-back-symbol)
		 '("c" . meow-change)
		 '("C" . meow-change-save)
		 '("e" . meow-prev)
		 '("E" . meow-prev-expand)
		 '("g" . meow-cancel-selection)
		 '("G" . meow-grab)
		 '("h" . meow-left)
		 '("H" . meow-left-expand)
		 '("i" . meow-right)
		 '("I" . meow-right-expand)
		 '("j" . meow-join)
		 '("k" . meow-kill)
		 '("l" . meow-line)
		 '("m" . meow-mark-word)
		 '("M" . meow-mark-symbol)
		 '("n" . meow-next)
		 '("N" . meow-next-expand)
		 '("o" . mewo-block)
		 '("O" . meow-to-block)
		 '("p" . meow-yank)
		 '("q" . delete-window)
		 '("r" . meow-replace)
		 '("R" . meow-replace-save)
		 '("s" . meow-insert)
		 '("S" . meow-open-below)
		 '("t" . meow-till)
		 '("u" . vundo)
		 '("U" . meow-undo-in-selection)
		 '("v" . meow-search)
		 '("w" . meow-next-word)
		 '("W" . meow-next-symbol)
		 '("x" . meow-delete)
		 '("X" . meow-backward-delete)
		 '("y" . meow-save)
		 '("z" . meow-pop-selection)
		 '("'" . repeat)
		 '("&" . meow-query-replace-regexp)
		 '("%" . meow-query-replace)
		 '("<escape>" . ignore))
		(:doc "setup meow leader keybindings")
		(:when-loaded
			(meow-leader-define-key
			 '("D" . global-command-log-mode)
			 '("e" . meow-eval-last-exp)
			 '("'" . meow-wrap-string)
			 '("@ u" . smerge-keep-upper)
			 '("@ l" . smerge-keep-lower)
			 '("@ a" . smerge-keep-all)
			 '("@ m" . smerge-keep-mine)
			 '("@ o" . smerge-keep-other)
			 '(";" . meow-comment)
			 '("(" . meow-wrap-round)
			 '("[" . meow-wrap-square)
			 '("{" . meow-wrap-curly)
			 '("}" . meow-forward-barf)
			 '(")" . meow-forward-slurp)
			 '("R" . meow-transpose-sexp)
			 '("I" . imenu-list)
			 '("i" . eli/select-images)
			 '("F" . projectile-find-file-in-directory)
			 '("l" . consult-ripgrep)
			 '("L" . meow-goto-line)
			 '("p" . projectile-find-file)
			 '("T" . vterm)
			 '("j" . meow-join-sexp)
			 '("w" . other-window)
			 '("b" . consult-buffer)
			 '("o" . delete-other-windows)
			 '("s" . meow-splice-sexp)
			 '("S" . meow-split-sexp)
			 '("k" . kill-current-buffer)
			 '("K" . kill-matching-buffers)
			 '("v" . magit)
			 '("-" . split-window-below)
			 '("=" . split-window-right)
			 '("," . meow-pop-marker)
			 '("." . meow-find-ref)
			 '("u" . meow-universal-argument)
			 '("1" . meow-digit-argument)
			 '("2" . meow-digit-argument)
			 '("3" . meow-digit-argument)
			 '("4" . meow-digit-argument)
			 '("5" . meow-digit-argument)
			 '("6" . meow-digit-argument)
			 '("7" . meow-digit-argument)
			 '("8" . meow-digit-argument)
			 '("9" . meow-digit-argument)
			 '("0" . meow-digit-argument)))
		(:doc "setup meow motion keybindings")
		(:when-loaded
			(meow-motion-overwrite-define-key
			 '("<escape>" . ignore)
			 '("/" . meow-visit)
			 '("1" . winum-select-window-1)
			 '("2" . winum-select-window-2)
			 '("3" . winum-select-window-3)
			 '("4" . winum-select-window-4)
			 '("5" . winum-select-window-5)
			 '("6" . winum-select-window-6)
			 '("7" . winum-select-window-7)
			 '("8" . winum-select-window-8)
			 '("9" . winum-select-window-9)
			 '("0" . winum-select-window-0)))))

(provide 'init-meow)
;;; init-meow.el ends here
